apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
  # Basically says 'I've got routing rules for you'
    kubernetes.io/ingress.class: nginx
    # Lets us use regex in paths
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    # Should have changed the /etc/hosts to match this
    - host: posts.com
      http:
        paths:
          - path: /posts/create
            backend:
              service:
                name: posts-clusterip-srv
                port: 4000
          - path: /posts
            backend:
              service:
                name: query-srv
                port: 4002
          # Our annotation lets us use this regex
          - path: /posts/?(.*)/comments
            backend:
              service:
                name: comments-srv
                port: 4001
          # Match all other paths
          - path: /?(.*)
            backend:
              service:
                  name: client-srv
                  port: 3000