apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  # Tells deployment how to find the pods to create
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        # Can be anything - just used for loggings
        - name: tickets
          image: sjoedwards1/tickets
          env:
            - name: JWT_KEY
              valueFrom:
                  secretKeyRef:
                    name: jwt-secret
                    key: JWT_KEY
            - name: MONGO_URI
              value: mongodb://tickets-mongo-srv:27017/tickets
---
# Define the clusterIP
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  # Don't define type - the default is the clusterIP service
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000