# Skaffold is a tool that runs outside of the cluster
apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    # When you change a file, its going to reapply the files
    # When skaffold is stopped, all the resources wil be removed
    manifests:
      - ./infra/k8s/*
build:
  #Local config
  local:
    # Don't push to dockerhub when re-building
    push: false
  artifacts:
  - image: sjoedwards1/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        # Mount this file if it exists, or rebuild the entire image
        - src: 'src/**/*.ts'
          dest: .
  - image: sjoedwards1/tickets
    context: tickets
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        # Mount this file if it exists, or rebuild the entire image
        - src: 'src/**/*.ts'
          dest: .

  - image: sjoedwards1/orders
    context: orders
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        # Mount this file if it exists, or rebuild the entire image
        - src: 'src/**/*.ts'
          dest: .
  - image: sjoedwards1/expiration
    context: expiration
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        # Mount this file if it exists, or rebuild the entire image
        - src: 'src/**/*.ts'
          dest: .
  - image: sjoedwards1/client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        # Mount this file if it exists, or rebuild the entire image
        - src: '**/*.js'
          dest: .

# # GCP Config
# build:
#   googleCloudBuild:
#     projectId: ticketing-dev-301012
#   local:
#   push: true
#   artifacts:
#   - image: us.gcr.io/ticketing-dev-301012/auth
#         context: auth
#         docker:
#           dockerfile: Dockerfile
#         sync:
#           manual:
#             - src: 'src/**/*.ts'
#               dest: .