name: tests-orders

on:
  pull_request:
    paths:
      - './ticketing/orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ticketing
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && yarn && npm run test:ci
