name: tests-auth

on:
  pull_request:
    paths:
      - './ticketing/auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ticketing
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && yarn && npm run test:ci
