name: tests

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ticketing
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && npm install && npm run test:ci        
